apiVersion: v1
kind: Service
metadata:
  name: devsu-demo-app
  namespace: devsu-demo
  labels:
    app: devsu-demo-app
  annotations:
    # Anotaciones para prometheus
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/api/actuator/prometheus"
spec:
  type: ClusterIP  # Tipo de servicio (ClusterIP para interno, LoadBalancer para externo)
  
  # Selector de pods
  selector:
    app: devsu-demo-app
  
  # Puertos expuestos
  ports:
  - name: http
    port: 8000        # Puerto del servicio
    targetPort: http  # Puerto del contenedor (8000)
    protocol: TCP
  
  # Session affinity (opcional)
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 horas

---
# Service adicional tipo NodePort para acceso local en Minikube
apiVersion: v1
kind: Service
metadata:
  name: devsu-demo-app-nodeport
  namespace: devsu-demo
  labels:
    app: devsu-demo-app
spec:
  type: NodePort
  selector:
    app: devsu-demo-app
  ports:
  - name: http
    port: 8000
    targetPort: http
    nodePort: 30080  # Puerto fijo para f√°cil acceso (30000-32767)
    protocol: TCP
